config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'users#home'
  # get 'employees/index'

  # get 'employees/show'

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :jobs do
    member do
      get :apply_for_job
      get :applied_users
      get :view
      get :cancel_applied
    end
  end
  resources :applied_users



  #  resources :employees


end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :applied_user, :foreign_key => 'job_id'
  validates :title, presence: true
  validates :post, presence: true


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
	  @job = Job.new
	end

	def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      flash[:success] = "You have submitted a new job"
      redirect_to @job
    else
      render 'new'
    end
  end

  def show

    @job = Job.find(params[:id])
    @exist  = current_user.applied_user
  end

  def index
    @jobs = Job.all.page(params[:page]).per(5)
    if current_user.has_role? :employee
         @empjobs = current_user.job.page(params[:page]).per(5)
    end

  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.user = current_user
    if @job.update_attributes(job_params)
      flash[:success] = "You have successfully updated your job"
      redirect_to @job
    else
      render 'edit'
    end
  end

  def apply_for_job
    puts "1111111"

    puts @exist.inspect
    if @exist.nil?
      @appliedjob = AppliedUser.new(user_id: current_user.id, job_id: params[:id])
      if @appliedjob.save
         UserMailer.welcome_email(current_user).deliver_now
         flash[:success] = "Your confirmation mail sended for this job"
      redirect_to root_url

      else
      @jobs
      end
    else

      flash[:success] = "You have applied for this job"
       redirect_to root_url
    end

  end

  def view
    job = Job.find(params[:id])
    @arr = Array.new
    @s = job.applied_user
    @s.each do |k|
      @arr.push k.user
    end
  end


  def applied_users
    @j = Array.new
    @myjob = current_user.job
    # @jobcount = @myjob.count
    @myjob.each do |my_job|
      @j.push my_job.title
      @apuser = my_job.applied_user
      @req = Array.new
      @apuser.each do |ap_user|
        @req.push ap_user.user
      end
    end
  end

  def cancel_applied
    jb = Job.find(params[:id])
    @c = current_user.applied_user.where(job_id: jb.id).first
    if @c.destroy
      redirect_to(root_url)
    else
      flash[:success] = "There is a problem to cancel applied job"
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :post, :experience, :salary)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/applied_users.html.erb
<div class="margin">
  <table class="users">
   <% if current_user.has_role? :employee %>
      <h1>All Applied Users</h1>
      <h3><%= @j.first %>:</h3>
      <% @req.each do |user| %>
        <tr>
         <td></td><td></td><td><%= user.email %></td> <td></td>
        </tr>
      <% end %>
   <% end %>
  </table>

</div>

app/views/jobs/edit.html.erb
<div class="margin">
  <h1>Update your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@job) do |f| %>

        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :post %>
        <%= f.text_field :post%>

        <%= f.label :experience %>
        <%= f.text_field :experience %>

        <%= f.label :salary %>
        <%= f.text_field :salary %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>


    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="margin">
  <% provide(:title, 'Apply') %>


  <table class="users">
   <% if current_user.has_role? :employee %>
      <h1>All My Jobs</h1>
      <% paginate @empjobs %>
      <% @empjobs.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.post %></td>
          <td><%= job.experience %></td>
          <td><%= job.salary %></td>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'View Users', view_job_path(job) %></td>
        </tr>
      <% end %>
    <% end %>
  </table>

  <table class="users">
   <% if current_user.has_role? :candidate %>
     <h1>All Jobs</h1>
     <%= paginate @jobs %>
     <% @jobs.each do |job| %>
       <tr>
          <td><%= job.title %></td> <td></td>
          <td><%= job.post %></td> <td></td>
          <td><%= job.experience %></td> <td></td>
          <td><%= job.salary %></td><td></td>

          <% if check_applied?(job.id) %>
            <td><%= link_to 'Apply', apply_for_job_job_path(job) %></td>
          <%else%>
            <td><%= link_to 'Cancel', cancel_applied_job_path(job.id) %></td>
          <% end %>
        </tr>
     <% end %>
    <% end %>
  </table>


</div>

app/views/jobs/new.html.erb
<% #provide(:title, 'Sign up') %>
<div class="margin">


  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@job,url:jobs_path) do |f| %>
        <h1>Create New Job</h1>
      <%= render 'shared/error_messages_job' %>

        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :post %>
        <%= f.text_field :post %>
        <%= f.label :experience %>
        <%= f.text_field :experience %>

        <%= f.label :salary %>
        <%= f.text_field :salary%>

        <%= f.submit "Create ", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="margin">
  <h1>Job Detail</h1>

  <table>
    <tr>
      <td>Title:</td>
      <td><%= @job.title %>
      </td>
    </tr>

    <tr>
      <td>Post:</td>
      <td><%= @job.post %></td>
    </tr>
    <tr>
      <td>Experience:</td>
      <td><%= @job.experience %></td>
    </tr>
    <tr>
      <td>salary:</td>
      <td><%= @job.salary %></td>
    </tr>
  </table>
</div>

app/views/jobs/view.html.erb
<div class="margin">

  <table class="users">
   <% if current_user.has_role? :employee %>
     <h1>All Applied Users</h1>
     <% @arr.each do |user| %>
        <tr>
         <td></td><td></td><td><%= user.email %></td> <td></td>
        </tr>
      <% end %>
    <% end %>
  </table>

</div>