config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  root 'users#home'
  # get 'employees/index'

  # get 'employees/show'

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :jobs do
    member do
      get :apply_for_job
      get :applied_users
      get :view
      get :cancel_applied
    end
  end
  resources :applied_users



  #  resources :employees


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/applied_user.rb
class AppliedUser < ApplicationRecord

  belongs_to :user
  belongs_to  :job
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :job
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :applied_user, :foreign_key => 'job_id'
  validates :title, presence: true
  validates :post, presence: true


end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true, :optional => true
  validates :resource_type,  :inclusion => { :in => Rolify.resource_types }, :allow_nil => true
  scopify
end

app/models/user.rb
class User < ApplicationRecord

  rolify

  has_many :job
  has_many :applied_user,   :foreign_key => 'user_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/applied_users_controller.rb
class AppliedUsersController < ApplicationController
  def new
   @apjob = AppliedUser.new
	end

	def create
    puts params[:current_job].inspect
    @appliedjob = AppliedUser.new(user_id: current_user.id, job_id: current_job)
    if @appliedjob.save
      flash[:success] = "You have successfully applied  for this job"
    end
	end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
  	@employee = Employee.new(user_params)
    if @employee.save
      flash[:success] = "You have successfully created!!!!!!!!"
      redirect_to @employee
    else
      render 'new'
    end
  end


  private
  def user_params
   params.require(:employee).permit(:name, :email, :password)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
	  @job = Job.new
	end

	def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      flash[:success] = "You have submitted a new job"
      redirect_to @job
    else
      render 'new'
    end
  end

  def show

    @job = Job.find(params[:id])
    @exist  = current_user.applied_user
  end

  def index
    @jobs = Job.all.page(params[:page]).per(5)
    if current_user.has_role? :employee
         @empjobs = current_user.job.page(params[:page]).per(5)
    end

  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.user = current_user
    if @job.update_attributes(job_params)
      flash[:success] = "You have successfully updated your job"
      redirect_to @job
    else
      render 'edit'
    end
  end

  def apply_for_job
    puts "1111111"

    puts @exist.inspect
    if @exist.nil?
      @appliedjob = AppliedUser.new(user_id: current_user.id, job_id: params[:id])
      if @appliedjob.save
         UserMailer.welcome_email(current_user).deliver_now
         flash[:success] = "Your confirmation mail sended for this job"
      redirect_to root_url

      else
      @jobs
      end
    else

      flash[:success] = "You have applied for this job"
       redirect_to root_url
    end

  end

  def view
    job = Job.find(params[:id])
    @arr = Array.new
    @s = job.applied_user
    @s.each do |k|
      @arr.push k.user
    end
  end


  def applied_users
    @j = Array.new
    @myjob = current_user.job
    # @jobcount = @myjob.count
    @myjob.each do |my_job|
      @j.push my_job.title
      @apuser = my_job.applied_user
      @req = Array.new
      @apuser.each do |ap_user|
        @req.push ap_user.user
      end
    end
  end

  def cancel_applied
    jb = Job.find(params[:id])
    @c = current_user.applied_user.where(job_id: jb.id).first
    if @c.destroy
      redirect_to(root_url)
    else
      flash[:success] = "There is a problem to cancel applied job"
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :post, :experience, :salary)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   # def create
   #  super
   # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action  :authenticate_user!, only: [:show, :edit]
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end

  def check_applied?(job_id)
  	@a = current_user.applied_user.where(job_id: job_id).first
  	if @a.nil?
  		true
  	else
  		false
    end
   end
end

app/helpers/applied_users_helper.rb
module AppliedUsersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Job Portal", root_url , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_url %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if user_signed_in? %>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </li>
          <% if current_user.has_role? :employee %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to('Create Job', new_job_path, method: :get) %> </li>
              <li class="divider"></li>
              <li><%= link_to('All My Jobs', jobs_path, method: :get) %></li>
              <!--<li class="divider"></li>
               <li><%= link_to('All Applied Users', applied_users_job_path(current_user.id)) %> </li>-->

            </ul>
          </li>
          <% else %>
              <li>
              <%= link_to('All Jobs', jobs_path, method: :get) %>
              </li>
          <% end %>
        <% else %>
         <li>
         <%= link_to('Login', new_user_session_path)  %>
         </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>

   <%= render "layouts/header" %>
   <% if notice %>
     <p class="alert alert-success"><%= notice %></p>
   <% end %>
   <% if alert %>
     <p class="alert alert-danger"><%= alert %></p>
   <% end %>
   <%= yield %>
  </body>
</html>

app/views/shared/_error_messages_employee.html.erb
<% if @employee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@employee.errors.count, "error") %>.
    </div>
    <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>

  </div>
<% end %>

app/views/shared/_error_messages_job.html.erb
<% if @job.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@job.errors.count, "error") %>.
    </div>
    <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
<% end %>